static const char *
names_opcode(u32 code)
{
    switch (code) {
        case 0: return("OpNop");
        case 1: return("OpUndef");
        case 2: return("OpSourceContinued");
        case 3: return("OpSource");
        case 4: return("OpSourceExtension");
        case 5: return("OpName");
        case 6: return("OpMemberName");
        case 7: return("OpString");
        case 8: return("OpLine");
        case 10: return("OpExtension");
        case 11: return("OpExtInstImport");
        case 12: return("OpExtInst");
        case 14: return("OpMemoryModel");
        case 15: return("OpEntryPoint");
        case 16: return("OpExecutionMode");
        case 17: return("OpCapability");
        case 19: return("OpTypeVoid");
        case 20: return("OpTypeBool");
        case 21: return("OpTypeInt");
        case 22: return("OpTypeFloat");
        case 23: return("OpTypeVector");
        case 24: return("OpTypeMatrix");
        case 25: return("OpTypeImage");
        case 26: return("OpTypeSampler");
        case 27: return("OpTypeSampledImage");
        case 28: return("OpTypeArray");
        case 29: return("OpTypeRuntimeArray");
        case 30: return("OpTypeStruct");
        case 31: return("OpTypeOpaque");
        case 32: return("OpTypePointer");
        case 33: return("OpTypeFunction");
        case 34: return("OpTypeEvent");
        case 35: return("OpTypeDeviceEvent");
        case 36: return("OpTypeReserveId");
        case 37: return("OpTypeQueue");
        case 38: return("OpTypePipe");
        case 39: return("OpTypeForwardPointer");
        case 41: return("OpConstantTrue");
        case 42: return("OpConstantFalse");
        case 43: return("OpConstant");
        case 44: return("OpConstantComposite");
        case 45: return("OpConstantSampler");
        case 46: return("OpConstantNull");
        case 48: return("OpSpecConstantTrue");
        case 49: return("OpSpecConstantFalse");
        case 50: return("OpSpecConstant");
        case 51: return("OpSpecConstantComposite");
        case 52: return("OpSpecConstantOp");
        case 54: return("OpFunction");
        case 55: return("OpFunctionParameter");
        case 56: return("OpFunctionEnd");
        case 57: return("OpFunctionCall");
        case 59: return("OpVariable");
        case 60: return("OpImageTexelPointer");
        case 61: return("OpLoad");
        case 62: return("OpStore");
        case 63: return("OpCopyMemory");
        case 64: return("OpCopyMemorySized");
        case 65: return("OpAccessChain");
        case 66: return("OpInBoundsAccessChain");
        case 67: return("OpPtrAccessChain");
        case 68: return("OpArrayLength");
        case 69: return("OpGenericPtrMemSemantics");
        case 70: return("OpInBoundsPtrAccessChain");
        case 71: return("OpDecorate");
        case 72: return("OpMemberDecorate");
        case 73: return("OpDecorationGroup");
        case 74: return("OpGroupDecorate");
        case 75: return("OpGroupMemberDecorate");
        case 77: return("OpVectorExtractDynamic");
        case 78: return("OpVectorInsertDynamic");
        case 79: return("OpVectorShuffle");
        case 80: return("OpCompositeConstruct");
        case 81: return("OpCompositeExtract");
        case 82: return("OpCompositeInsert");
        case 83: return("OpCopyObject");
        case 84: return("OpTranspose");
        case 86: return("OpSampledImage");
        case 87: return("OpImageSampleImplicitLod");
        case 88: return("OpImageSampleExplicitLod");
        case 89: return("OpImageSampleDrefImplicitLod");
        case 90: return("OpImageSampleDrefExplicitLod");
        case 91: return("OpImageSampleProjImplicitLod");
        case 92: return("OpImageSampleProjExplicitLod");
        case 93: return("OpImageSampleProjDrefImplicitLod");
        case 94: return("OpImageSampleProjDrefExplicitLod");
        case 95: return("OpImageFetch");
        case 96: return("OpImageGather");
        case 97: return("OpImageDrefGather");
        case 98: return("OpImageRead");
        case 99: return("OpImageWrite");
        case 100: return("OpImage");
        case 101: return("OpImageQueryFormat");
        case 102: return("OpImageQueryOrder");
        case 103: return("OpImageQuerySizeLod");
        case 104: return("OpImageQuerySize");
        case 105: return("OpImageQueryLod");
        case 106: return("OpImageQueryLevels");
        case 107: return("OpImageQuerySamples");
        case 109: return("OpConvertFToU");
        case 110: return("OpConvertFToS");
        case 111: return("OpConvertSToF");
        case 112: return("OpConvertUToF");
        case 113: return("OpUConvert");
        case 114: return("OpSConvert");
        case 115: return("OpFConvert");
        case 116: return("OpQuantizeToF16");
        case 117: return("OpConvertPtrToU");
        case 118: return("OpSatConvertSToU");
        case 119: return("OpSatConvertUToS");
        case 120: return("OpConvertUToPtr");
        case 121: return("OpPtrCastToGeneric");
        case 122: return("OpGenericCastToPtr");
        case 123: return("OpGenericCastToPtrExplicit");
        case 124: return("OpBitcast");
        case 126: return("OpSNegate");
        case 127: return("OpFNegate");
        case 128: return("OpIAdd");
        case 129: return("OpFAdd");
        case 130: return("OpISub");
        case 131: return("OpFSub");
        case 132: return("OpIMul");
        case 133: return("OpFMul");
        case 134: return("OpUDiv");
        case 135: return("OpSDiv");
        case 136: return("OpFDiv");
        case 137: return("OpUMod");
        case 138: return("OpSRem");
        case 139: return("OpSMod");
        case 140: return("OpFRem");
        case 141: return("OpFMod");
        case 142: return("OpVectorTimesScalar");
        case 143: return("OpMatrixTimesScalar");
        case 144: return("OpVectorTimesMatrix");
        case 145: return("OpMatrixTimesVector");
        case 146: return("OpMatrixTimesMatrix");
        case 147: return("OpOuterProduct");
        case 148: return("OpDot");
        case 149: return("OpIAddCarry");
        case 150: return("OpISubBorrow");
        case 151: return("OpUMulExtended");
        case 152: return("OpSMulExtended");
        case 154: return("OpAny");
        case 155: return("OpAll");
        case 156: return("OpIsNan");
        case 157: return("OpIsInf");
        case 158: return("OpIsFinite");
        case 159: return("OpIsNormal");
        case 160: return("OpSignBitSet");
        case 161: return("OpLessOrGreater");
        case 162: return("OpOrdered");
        case 163: return("OpUnordered");
        case 164: return("OpLogicalEqual");
        case 165: return("OpLogicalNotEqual");
        case 166: return("OpLogicalOr");
        case 167: return("OpLogicalAnd");
        case 168: return("OpLogicalNot");
        case 169: return("OpSelect");
        case 170: return("OpIEqual");
        case 171: return("OpINotEqual");
        case 172: return("OpUGreaterThan");
        case 173: return("OpSGreaterThan");
        case 174: return("OpUGreaterThanEqual");
        case 175: return("OpSGreaterThanEqual");
        case 176: return("OpULessThan");
        case 177: return("OpSLessThan");
        case 178: return("OpULessThanEqual");
        case 179: return("OpSLessThanEqual");
        case 180: return("OpFOrdEqual");
        case 181: return("OpFUnordEqual");
        case 182: return("OpFOrdNotEqual");
        case 183: return("OpFUnordNotEqual");
        case 184: return("OpFOrdLessThan");
        case 185: return("OpFUnordLessThan");
        case 186: return("OpFOrdGreaterThan");
        case 187: return("OpFUnordGreaterThan");
        case 188: return("OpFOrdLessThanEqual");
        case 189: return("OpFUnordLessThanEqual");
        case 190: return("OpFOrdGreaterThanEqual");
        case 191: return("OpFUnordGreaterThanEqual");
        case 194: return("OpShiftRightLogical");
        case 195: return("OpShiftRightArithmetic");
        case 196: return("OpShiftLeftLogical");
        case 197: return("OpBitwiseOr");
        case 198: return("OpBitwiseXor");
        case 199: return("OpBitwiseAnd");
        case 200: return("OpNot");
        case 201: return("OpBitFieldInsert");
        case 202: return("OpBitFieldSExtract");
        case 203: return("OpBitFieldUExtract");
        case 204: return("OpBitReverse");
        case 205: return("OpBitCount");
        case 207: return("OpDPdx");
        case 208: return("OpDPdy");
        case 209: return("OpFwidth");
        case 210: return("OpDPdxFine");
        case 211: return("OpDPdyFine");
        case 212: return("OpFwidthFine");
        case 213: return("OpDPdxCoarse");
        case 214: return("OpDPdyCoarse");
        case 215: return("OpFwidthCoarse");
        case 218: return("OpEmitVertex");
        case 219: return("OpEndPrimitive");
        case 220: return("OpEmitStreamVertex");
        case 221: return("OpEndStreamPrimitive");
        case 224: return("OpControlBarrier");
        case 225: return("OpMemoryBarrier");
        case 227: return("OpAtomicLoad");
        case 228: return("OpAtomicStore");
        case 229: return("OpAtomicExchange");
        case 230: return("OpAtomicCompareExchange");
        case 231: return("OpAtomicCompareExchangeWeak");
        case 232: return("OpAtomicIIncrement");
        case 233: return("OpAtomicIDecrement");
        case 234: return("OpAtomicIAdd");
        case 235: return("OpAtomicISub");
        case 236: return("OpAtomicSMin");
        case 237: return("OpAtomicUMin");
        case 238: return("OpAtomicSMax");
        case 239: return("OpAtomicUMax");
        case 240: return("OpAtomicAnd");
        case 241: return("OpAtomicOr");
        case 242: return("OpAtomicXor");
        case 245: return("OpPhi");
        case 246: return("OpLoopMerge");
        case 247: return("OpSelectionMerge");
        case 248: return("OpLabel");
        case 249: return("OpBranch");
        case 250: return("OpBranchConditional");
        case 251: return("OpSwitch");
        case 252: return("OpKill");
        case 253: return("OpReturn");
        case 254: return("OpReturnValue");
        case 255: return("OpUnreachable");
        case 256: return("OpLifetimeStart");
        case 257: return("OpLifetimeStop");
        case 259: return("OpGroupAsyncCopy");
        case 260: return("OpGroupWaitEvents");
        case 261: return("OpGroupAll");
        case 262: return("OpGroupAny");
        case 263: return("OpGroupBroadcast");
        case 264: return("OpGroupIAdd");
        case 265: return("OpGroupFAdd");
        case 266: return("OpGroupFMin");
        case 267: return("OpGroupUMin");
        case 268: return("OpGroupSMin");
        case 269: return("OpGroupFMax");
        case 270: return("OpGroupUMax");
        case 271: return("OpGroupSMax");
        case 274: return("OpReadPipe");
        case 275: return("OpWritePipe");
        case 276: return("OpReservedReadPipe");
        case 277: return("OpReservedWritePipe");
        case 278: return("OpReserveReadPipePackets");
        case 279: return("OpReserveWritePipePackets");
        case 280: return("OpCommitReadPipe");
        case 281: return("OpCommitWritePipe");
        case 282: return("OpIsValidReserveId");
        case 283: return("OpGetNumPipePackets");
        case 284: return("OpGetMaxPipePackets");
        case 285: return("OpGroupReserveReadPipePackets");
        case 286: return("OpGroupReserveWritePipePackets");
        case 287: return("OpGroupCommitReadPipe");
        case 288: return("OpGroupCommitWritePipe");
        case 291: return("OpEnqueueMarker");
        case 292: return("OpEnqueueKernel");
        case 293: return("OpGetKernelNDrangeSubGroupCount");
        case 294: return("OpGetKernelNDrangeMaxSubGroupSize");
        case 295: return("OpGetKernelWorkGroupSize");
        case 296: return("OpGetKernelPreferredWorkGroupSizeMultiple");
        case 297: return("OpRetainEvent");
        case 298: return("OpReleaseEvent");
        case 299: return("OpCreateUserEvent");
        case 300: return("OpIsValidEvent");
        case 301: return("OpSetUserEventStatus");
        case 302: return("OpCaptureEventProfilingInfo");
        case 303: return("OpGetDefaultQueue");
        case 304: return("OpBuildNDRange");
        case 305: return("OpImageSparseSampleImplicitLod");
        case 306: return("OpImageSparseSampleExplicitLod");
        case 307: return("OpImageSparseSampleDrefImplicitLod");
        case 308: return("OpImageSparseSampleDrefExplicitLod");
        case 309: return("OpImageSparseSampleProjImplicitLod");
        case 310: return("OpImageSparseSampleProjExplicitLod");
        case 311: return("OpImageSparseSampleProjDrefImplicitLod");
        case 312: return("OpImageSparseSampleProjDrefExplicitLod");
        case 313: return("OpImageSparseFetch");
        case 314: return("OpImageSparseGather");
        case 315: return("OpImageSparseDrefGather");
        case 316: return("OpImageSparseTexelsResident");
        case 317: return("OpNoLine");
        case 318: return("OpAtomicFlagTestAndSet");
        case 319: return("OpAtomicFlagClear");
        case 320: return("OpImageSparseRead");
        case 321: return("OpSizeOf");
        case 322: return("OpTypePipeStorage");
        case 323: return("OpConstantPipeStorage");
        case 324: return("OpCreatePipeFromPipeStorage");
        case 325: return("OpGetKernelLocalSizeForSubgroupCount");
        case 326: return("OpGetKernelMaxNumSubgroups");
        case 327: return("OpTypeNamedBarrier");
        case 328: return("OpNamedBarrierInitialize");
        case 329: return("OpMemoryNamedBarrier");
        case 330: return("OpModuleProcessed");
        case 331: return("OpExecutionModeId");
        case 332: return("OpDecorateId");
        case 333: return("OpGroupNonUniformElect");
        case 334: return("OpGroupNonUniformAll");
        case 335: return("OpGroupNonUniformAny");
        case 336: return("OpGroupNonUniformAllEqual");
        case 337: return("OpGroupNonUniformBroadcast");
        case 338: return("OpGroupNonUniformBroadcastFirst");
        case 339: return("OpGroupNonUniformBallot");
        case 340: return("OpGroupNonUniformInverseBallot");
        case 341: return("OpGroupNonUniformBallotBitExtract");
        case 342: return("OpGroupNonUniformBallotBitCount");
        case 343: return("OpGroupNonUniformBallotFindLSB");
        case 344: return("OpGroupNonUniformBallotFindMSB");
        case 345: return("OpGroupNonUniformShuffle");
        case 346: return("OpGroupNonUniformShuffleXor");
        case 347: return("OpGroupNonUniformShuffleUp");
        case 348: return("OpGroupNonUniformShuffleDown");
        case 349: return("OpGroupNonUniformIAdd");
        case 350: return("OpGroupNonUniformFAdd");
        case 351: return("OpGroupNonUniformIMul");
        case 352: return("OpGroupNonUniformFMul");
        case 353: return("OpGroupNonUniformSMin");
        case 354: return("OpGroupNonUniformUMin");
        case 355: return("OpGroupNonUniformFMin");
        case 356: return("OpGroupNonUniformSMax");
        case 357: return("OpGroupNonUniformUMax");
        case 358: return("OpGroupNonUniformFMax");
        case 359: return("OpGroupNonUniformBitwiseAnd");
        case 360: return("OpGroupNonUniformBitwiseOr");
        case 361: return("OpGroupNonUniformBitwiseXor");
        case 362: return("OpGroupNonUniformLogicalAnd");
        case 363: return("OpGroupNonUniformLogicalOr");
        case 364: return("OpGroupNonUniformLogicalXor");
        case 365: return("OpGroupNonUniformQuadBroadcast");
        case 366: return("OpGroupNonUniformQuadSwap");
        case 4421: return("OpSubgroupBallotKHR");
        case 4422: return("OpSubgroupFirstInvocationKHR");
        case 4428: return("OpSubgroupAllKHR");
        case 4429: return("OpSubgroupAnyKHR");
        case 4430: return("OpSubgroupAllEqualKHR");
        case 4432: return("OpSubgroupReadInvocationKHR");
        case 5000: return("OpGroupIAddNonUniformAMD");
        case 5001: return("OpGroupFAddNonUniformAMD");
        case 5002: return("OpGroupFMinNonUniformAMD");
        case 5003: return("OpGroupUMinNonUniformAMD");
        case 5004: return("OpGroupSMinNonUniformAMD");
        case 5005: return("OpGroupFMaxNonUniformAMD");
        case 5006: return("OpGroupUMaxNonUniformAMD");
        case 5007: return("OpGroupSMaxNonUniformAMD");
        case 5011: return("OpFragmentMaskFetchAMD");
        case 5012: return("OpFragmentFetchAMD");
        case 5283: return("OpImageSampleFootprintNV");
        case 5296: return("OpGroupNonUniformPartitionNV");
        case 5299: return("OpWritePackedPrimitiveIndices4x8NV");
        case 5334: return("OpReportIntersectionNV");
        case 5335: return("OpIgnoreIntersectionNV");
        case 5336: return("OpTerminateRayNV");
        case 5337: return("OpTraceNV");
        case 5341: return("OpTypeAccelerationStructureNV");
        case 5344: return("OpExecuteCallableNV");
        case 5571: return("OpSubgroupShuffleINTEL");
        case 5572: return("OpSubgroupShuffleDownINTEL");
        case 5573: return("OpSubgroupShuffleUpINTEL");
        case 5574: return("OpSubgroupShuffleXorINTEL");
        case 5575: return("OpSubgroupBlockReadINTEL");
        case 5576: return("OpSubgroupBlockWriteINTEL");
        case 5577: return("OpSubgroupImageBlockReadINTEL");
        case 5578: return("OpSubgroupImageBlockWriteINTEL");
        case 5580: return("OpSubgroupImageMediaBlockReadINTEL");
        case 5581: return("OpSubgroupImageMediaBlockWriteINTEL");
        case 5632: return("OpDecorateStringGOOGLE");
        case 5633: return("OpMemberDecorateStringGOOGLE");
        case 0x7fffffff: return("OpMax");
    }
    
    return(NULL);
}

enum Op {
    OpNop = 0,
    OpUndef = 1,
    OpSourceContinued = 2,
    OpSource = 3,
    OpSourceExtension = 4,
    OpName = 5,
    OpMemberName = 6,
    OpString = 7,
    OpLine = 8,
    OpExtension = 10,
    OpExtInstImport = 11,
    OpExtInst = 12,
    OpMemoryModel = 14,
    OpEntryPoint = 15,
    OpExecutionMode = 16,
    OpCapability = 17,
    OpTypeVoid = 19,
    OpTypeBool = 20,
    OpTypeInt = 21,
    OpTypeFloat = 22,
    OpTypeVector = 23,
    OpTypeMatrix = 24,
    OpTypeImage = 25,
    OpTypeSampler = 26,
    OpTypeSampledImage = 27,
    OpTypeArray = 28,
    OpTypeRuntimeArray = 29,
    OpTypeStruct = 30,
    OpTypeOpaque = 31,
    OpTypePointer = 32,
    OpTypeFunction = 33,
    OpTypeEvent = 34,
    OpTypeDeviceEvent = 35,
    OpTypeReserveId = 36,
    OpTypeQueue = 37,
    OpTypePipe = 38,
    OpTypeForwardPointer = 39,
    OpConstantTrue = 41,
    OpConstantFalse = 42,
    OpConstant = 43,
    OpConstantComposite = 44,
    OpConstantSampler = 45,
    OpConstantNull = 46,
    OpSpecConstantTrue = 48,
    OpSpecConstantFalse = 49,
    OpSpecConstant = 50,
    OpSpecConstantComposite = 51,
    OpSpecConstantOp = 52,
    OpFunction = 54,
    OpFunctionParameter = 55,
    OpFunctionEnd = 56,
    OpFunctionCall = 57,
    OpVariable = 59,
    OpImageTexelPointer = 60,
    OpLoad = 61,
    OpStore = 62,
    OpCopyMemory = 63,
    OpCopyMemorySized = 64,
    OpAccessChain = 65,
    OpInBoundsAccessChain = 66,
    OpPtrAccessChain = 67,
    OpArrayLength = 68,
    OpGenericPtrMemSemantics = 69,
    OpInBoundsPtrAccessChain = 70,
    OpDecorate = 71,
    OpMemberDecorate = 72,
    OpDecorationGroup = 73,
    OpGroupDecorate = 74,
    OpGroupMemberDecorate = 75,
    OpVectorExtractDynamic = 77,
    OpVectorInsertDynamic = 78,
    OpVectorShuffle = 79,
    OpCompositeConstruct = 80,
    OpCompositeExtract = 81,
    OpCompositeInsert = 82,
    OpCopyObject = 83,
    OpTranspose = 84,
    OpSampledImage = 86,
    OpImageSampleImplicitLod = 87,
    OpImageSampleExplicitLod = 88,
    OpImageSampleDrefImplicitLod = 89,
    OpImageSampleDrefExplicitLod = 90,
    OpImageSampleProjImplicitLod = 91,
    OpImageSampleProjExplicitLod = 92,
    OpImageSampleProjDrefImplicitLod = 93,
    OpImageSampleProjDrefExplicitLod = 94,
    OpImageFetch = 95,
    OpImageGather = 96,
    OpImageDrefGather = 97,
    OpImageRead = 98,
    OpImageWrite = 99,
    OpImage = 100,
    OpImageQueryFormat = 101,
    OpImageQueryOrder = 102,
    OpImageQuerySizeLod = 103,
    OpImageQuerySize = 104,
    OpImageQueryLod = 105,
    OpImageQueryLevels = 106,
    OpImageQuerySamples = 107,
    OpConvertFToU = 109,
    OpConvertFToS = 110,
    OpConvertSToF = 111,
    OpConvertUToF = 112,
    OpUConvert = 113,
    OpSConvert = 114,
    OpFConvert = 115,
    OpQuantizeToF16 = 116,
    OpConvertPtrToU = 117,
    OpSatConvertSToU = 118,
    OpSatConvertUToS = 119,
    OpConvertUToPtr = 120,
    OpPtrCastToGeneric = 121,
    OpGenericCastToPtr = 122,
    OpGenericCastToPtrExplicit = 123,
    OpBitcast = 124,
    OpSNegate = 126,
    OpFNegate = 127,
    OpIAdd = 128,
    OpFAdd = 129,
    OpISub = 130,
    OpFSub = 131,
    OpIMul = 132,
    OpFMul = 133,
    OpUDiv = 134,
    OpSDiv = 135,
    OpFDiv = 136,
    OpUMod = 137,
    OpSRem = 138,
    OpSMod = 139,
    OpFRem = 140,
    OpFMod = 141,
    OpVectorTimesScalar = 142,
    OpMatrixTimesScalar = 143,
    OpVectorTimesMatrix = 144,
    OpMatrixTimesVector = 145,
    OpMatrixTimesMatrix = 146,
    OpOuterProduct = 147,
    OpDot = 148,
    OpIAddCarry = 149,
    OpISubBorrow = 150,
    OpUMulExtended = 151,
    OpSMulExtended = 152,
    OpAny = 154,
    OpAll = 155,
    OpIsNan = 156,
    OpIsInf = 157,
    OpIsFinite = 158,
    OpIsNormal = 159,
    OpSignBitSet = 160,
    OpLessOrGreater = 161,
    OpOrdered = 162,
    OpUnordered = 163,
    OpLogicalEqual = 164,
    OpLogicalNotEqual = 165,
    OpLogicalOr = 166,
    OpLogicalAnd = 167,
    OpLogicalNot = 168,
    OpSelect = 169,
    OpIEqual = 170,
    OpINotEqual = 171,
    OpUGreaterThan = 172,
    OpSGreaterThan = 173,
    OpUGreaterThanEqual = 174,
    OpSGreaterThanEqual = 175,
    OpULessThan = 176,
    OpSLessThan = 177,
    OpULessThanEqual = 178,
    OpSLessThanEqual = 179,
    OpFOrdEqual = 180,
    OpFUnordEqual = 181,
    OpFOrdNotEqual = 182,
    OpFUnordNotEqual = 183,
    OpFOrdLessThan = 184,
    OpFUnordLessThan = 185,
    OpFOrdGreaterThan = 186,
    OpFUnordGreaterThan = 187,
    OpFOrdLessThanEqual = 188,
    OpFUnordLessThanEqual = 189,
    OpFOrdGreaterThanEqual = 190,
    OpFUnordGreaterThanEqual = 191,
    OpShiftRightLogical = 194,
    OpShiftRightArithmetic = 195,
    OpShiftLeftLogical = 196,
    OpBitwiseOr = 197,
    OpBitwiseXor = 198,
    OpBitwiseAnd = 199,
    OpNot = 200,
    OpBitFieldInsert = 201,
    OpBitFieldSExtract = 202,
    OpBitFieldUExtract = 203,
    OpBitReverse = 204,
    OpBitCount = 205,
    OpDPdx = 207,
    OpDPdy = 208,
    OpFwidth = 209,
    OpDPdxFine = 210,
    OpDPdyFine = 211,
    OpFwidthFine = 212,
    OpDPdxCoarse = 213,
    OpDPdyCoarse = 214,
    OpFwidthCoarse = 215,
    OpEmitVertex = 218,
    OpEndPrimitive = 219,
    OpEmitStreamVertex = 220,
    OpEndStreamPrimitive = 221,
    OpControlBarrier = 224,
    OpMemoryBarrier = 225,
    OpAtomicLoad = 227,
    OpAtomicStore = 228,
    OpAtomicExchange = 229,
    OpAtomicCompareExchange = 230,
    OpAtomicCompareExchangeWeak = 231,
    OpAtomicIIncrement = 232,
    OpAtomicIDecrement = 233,
    OpAtomicIAdd = 234,
    OpAtomicISub = 235,
    OpAtomicSMin = 236,
    OpAtomicUMin = 237,
    OpAtomicSMax = 238,
    OpAtomicUMax = 239,
    OpAtomicAnd = 240,
    OpAtomicOr = 241,
    OpAtomicXor = 242,
    OpPhi = 245,
    OpLoopMerge = 246,
    OpSelectionMerge = 247,
    OpLabel = 248,
    OpBranch = 249,
    OpBranchConditional = 250,
    OpSwitch = 251,
    OpKill = 252,
    OpReturn = 253,
    OpReturnValue = 254,
    OpUnreachable = 255,
    OpLifetimeStart = 256,
    OpLifetimeStop = 257,
    OpGroupAsyncCopy = 259,
    OpGroupWaitEvents = 260,
    OpGroupAll = 261,
    OpGroupAny = 262,
    OpGroupBroadcast = 263,
    OpGroupIAdd = 264,
    OpGroupFAdd = 265,
    OpGroupFMin = 266,
    OpGroupUMin = 267,
    OpGroupSMin = 268,
    OpGroupFMax = 269,
    OpGroupUMax = 270,
    OpGroupSMax = 271,
    OpReadPipe = 274,
    OpWritePipe = 275,
    OpReservedReadPipe = 276,
    OpReservedWritePipe = 277,
    OpReserveReadPipePackets = 278,
    OpReserveWritePipePackets = 279,
    OpCommitReadPipe = 280,
    OpCommitWritePipe = 281,
    OpIsValidReserveId = 282,
    OpGetNumPipePackets = 283,
    OpGetMaxPipePackets = 284,
    OpGroupReserveReadPipePackets = 285,
    OpGroupReserveWritePipePackets = 286,
    OpGroupCommitReadPipe = 287,
    OpGroupCommitWritePipe = 288,
    OpEnqueueMarker = 291,
    OpEnqueueKernel = 292,
    OpGetKernelNDrangeSubGroupCount = 293,
    OpGetKernelNDrangeMaxSubGroupSize = 294,
    OpGetKernelWorkGroupSize = 295,
    OpGetKernelPreferredWorkGroupSizeMultiple = 296,
    OpRetainEvent = 297,
    OpReleaseEvent = 298,
    OpCreateUserEvent = 299,
    OpIsValidEvent = 300,
    OpSetUserEventStatus = 301,
    OpCaptureEventProfilingInfo = 302,
    OpGetDefaultQueue = 303,
    OpBuildNDRange = 304,
    OpImageSparseSampleImplicitLod = 305,
    OpImageSparseSampleExplicitLod = 306,
    OpImageSparseSampleDrefImplicitLod = 307,
    OpImageSparseSampleDrefExplicitLod = 308,
    OpImageSparseSampleProjImplicitLod = 309,
    OpImageSparseSampleProjExplicitLod = 310,
    OpImageSparseSampleProjDrefImplicitLod = 311,
    OpImageSparseSampleProjDrefExplicitLod = 312,
    OpImageSparseFetch = 313,
    OpImageSparseGather = 314,
    OpImageSparseDrefGather = 315,
    OpImageSparseTexelsResident = 316,
    OpNoLine = 317,
    OpAtomicFlagTestAndSet = 318,
    OpAtomicFlagClear = 319,
    OpImageSparseRead = 320,
    OpSizeOf = 321,
    OpTypePipeStorage = 322,
    OpConstantPipeStorage = 323,
    OpCreatePipeFromPipeStorage = 324,
    OpGetKernelLocalSizeForSubgroupCount = 325,
    OpGetKernelMaxNumSubgroups = 326,
    OpTypeNamedBarrier = 327,
    OpNamedBarrierInitialize = 328,
    OpMemoryNamedBarrier = 329,
    OpModuleProcessed = 330,
    OpExecutionModeId = 331,
    OpDecorateId = 332,
    OpSubgroupBallotKHR = 4421,
    OpSubgroupFirstInvocationKHR = 4422,
    OpSubgroupAllKHR = 4428,
    OpSubgroupAnyKHR = 4429,
    OpSubgroupAllEqualKHR = 4430,
    OpSubgroupReadInvocationKHR = 4432,
    OpGroupIAddNonUniformAMD = 5000,
    OpGroupFAddNonUniformAMD = 5001,
    OpGroupFMinNonUniformAMD = 5002,
    OpGroupUMinNonUniformAMD = 5003,
    OpGroupSMinNonUniformAMD = 5004,
    OpGroupFMaxNonUniformAMD = 5005,
    OpGroupUMaxNonUniformAMD = 5006,
    OpGroupSMaxNonUniformAMD = 5007,
    OpFragmentMaskFetchAMD = 5011,
    OpFragmentFetchAMD = 5012,
    OpSubgroupShuffleINTEL = 5571,
    OpSubgroupShuffleDownINTEL = 5572,
    OpSubgroupShuffleUpINTEL = 5573,
    OpSubgroupShuffleXorINTEL = 5574,
    OpSubgroupBlockReadINTEL = 5575,
    OpSubgroupBlockWriteINTEL = 5576,
    OpSubgroupImageBlockReadINTEL = 5577,
    OpSubgroupImageBlockWriteINTEL = 5578,
    OpDecorateStringGOOGLE = 5632,
    OpMemberDecorateStringGOOGLE = 5633,
    OpMax = 0x7fffffff,
};
